name: Code quality and unit testing
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  code_quality_testing:
    name: Code quality and unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo and setup
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Tests for PR success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: 'Tests for PR ${{ github.event.pull_request.url }} of ${{ github.event.repository.name }} successfully executed'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://cdn.discordapp.com/avatars/839863605943205949/37ee1fdc2ea3909e3e1da4d109fbfa65.webp?size=256
      - name: Tests for PR failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: 'Tests for PR ${{ github.event.url }} of ${{ github.event.repository.name }} failed'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://cdn.discordapp.com/avatars/839863605943205949/37ee1fdc2ea3909e3e1da4d109fbfa65.webp?size=256
      - name: Tests for PR cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: 'Tests for PR ${{ github.event.url }} of ${{ github.event.repository.name }} cancelled'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          avatarUrl: https://cdn.discordapp.com/avatars/839863605943205949/37ee1fdc2ea3909e3e1da4d109fbfa65.webp?size=256
